### ISSUE TITLE
Ugly Desktop Icons with GTK+3 3.22.12

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-icon-theme#23]
I just upgraded my Slackware laptop to GTK+3 3.22.12 and i upgraded mate-themes to 3.22.10 to match the GTK+3 version.

This is my new laptop icons and it seems to have a shadow and it's ugly.
![mate-icon-themes](https://cloud.githubusercontent.com/assets/240100/25475357/a9710db8-2b60-11e7-9d5e-bde044b7136b.jpg)

here's what it looks like in GTK+3 3.18.9
![mate1](https://cloud.githubusercontent.com/assets/240100/25475480/18581a28-2b61-11e7-9a13-a7630d3c6cec.png)

Tested with default Menta theme

**Comment by willysr** [comment]
Strange thing is that i tried to test it on my workstation at the office and it looks just fine
![mate](https://cloud.githubusercontent.com/assets/240100/25476395/4631614a-2b64-11e7-9cfe-255f63f34f73.jpg)

i wonder if it only affect laptops?

**Comment by lukefromdc** [comment]
What version of Caja do you have installed, and was it updated with or after GTK 3.22 was installed? If you have caja 1.14 or earlier, or any version of Caja built with GTK 3.20 or earlier you will have this issue, as it is one of the symptoms of 
https://github.com/mate-desktop/caja/issues/575
which was fixed in 1.16 and later. Caja must be built with GTK 3.22 for the fix to be used, as changes to internal GTK3 code required changes to Caja that could have cause problems with older versions of GTK3.  Thus, if you updated to GTK3.22 but did not update Caja you will get very dark shadows on desktop icons-and if you try to move an icon the old position will also still be shoting.

**Comment by willysr** [comment]
I'm using latest 1.18.x but i haven't rebuilt against latest GTK+3.
I will try to update it tomorrow on my laptop, but strange thing is that it only happened on my laptop. On two of my workstation and desktop, that issue didn't occur even though it uses the same configuration

**Comment by lukefromdc** [comment]
Try moving an icon on the desktop on one of those other machines. If they have the older Caja and GTK 3.22 you should see it in both the old and new locations. If no shadows are use at all with the theme on those it could explain that, as there would be nothing to draw over and over again. I've never once seen Caja 1.14 or earlier, nor any version built with GTK 3.20 or earlier work right with GTK 3.22

**Comment by lukefromdc** [comment]
Also make sure Caja and not Nemo or Nautilus is managing the desktop on those other machines

**Comment by willysr** [comment]
@lukefromdc yes, you are right. When i hovered the desktop icons using caja built against earlier GTK+3, it has a strange behaviour on my desktop. I will try to rebuilt caja and see if it fixed it.

Thanks

**Comment by willysr** [comment]
after latest update of freetype and rebuilding all MATE against latest GTK+3, including caja fixed the problem.

Closing this issue
