### ISSUE TITLE
Missing icons for Synaptic in Control Center

### ISSUE THREAD

**Issue by BrentLauert** [mate-desktop/mate-icon-theme#24]
Ubuntu Mate 17.04
When choosing this icon theme, the icons for Synaptic and "additional drivers" are missing in Mate control center.

![bildschirmfoto zu 2017-05-14 10-32-30](https://cloud.githubusercontent.com/assets/8302465/26032321/b88b1d7e-3890-11e7-84c2-6cb2b620487d.png)

close control center choose different icon set (Ambiant-Mate here) and reopen. everything is fine:
![bildschirmfoto zu 2017-05-14 10-37-27](https://cloud.githubusercontent.com/assets/8302465/26032348/76c5d518-3891-11e7-83d6-36ccce12fc4d.png)

**Comment by flexiondotorg** [comment]
You need to file this bug with what ever icon theme exhibits the issue. It is incomplete.

**Comment by BrentLauert** [comment]
Ok, it is "MATE" icon theme. Post updated.

**Comment by lukefromdc** [comment]
In mate-icon-theme 1.19 as of 4-20-2017, selecting the MATE icon theme in mate-control-center brings up a valid icon for Synaptic.  The icon appears to be /usr/share/pixmaps/synaptic.png and is shipped with synaptic itself in Debian. This is the default icon, not one shipped by any theme, as is normal for applications. All icon themes should show it unless they ship an icon explicitly for synaptic.  The packages.ubuntu.com website shows you should have the exact same version of Synaptic I have, which is the 0.84.2 package and includes  /usr/share/pixmaps/synaptic.png .

 Since I don't have any proprietary drivers or helper programs to find them installed, I don't have an "additional drivers" entry in the control center.

**Comment by monsta** [comment]
I can reproduce the issue with Synaptic in Debian Testing and Ubuntu 16.10/17.04, but I have to restart m-c-c for that. Weird. Anyway, it's reproducible with MATE, Menta and GNOME icon themes. Since the theme doesn't have to have an icon for Synaptic, I would suggest opening an issue in m-c-c.

Also I can't reproduce the issue in GTK+2 build of MATE 1.16.

As for the Additional Drivers tool, the icon name used there is "jockey". The tool itself is in software-properties-gtk package, but they don't seem to ship a default icon inside. I don't think this can be solved only on our side.

**Comment by lukefromdc** [comment]
I can confirm you have to restart m-cc to make the icon appear or disappear. Simply changing the theme causes the correct icon to appear if and only if an icon was initially showing, so that looks like a problem in m-c-c with finding the icon.

**Comment by monsta** [comment]
Opened a new issue at https://github.com/mate-desktop/mate-control-center/issues/283.

**Comment by monsta** [comment]
Fix is released in m-c-c 1.18.2 now.
